config/routes.rb
Rails.application.routes.draw do
  get 'card_tiles/update'
  resources :lobbies do
    post :generate_tiles, on: :member
    resources :tiles, except: [:index, :show]
    resources :cards, except: [:index] do
      resources :tiles, controller: :card_tiles, only: [:update]
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lobbies#index"
end

app/models/lobby.rb
class Lobby < ApplicationRecord
  has_many :cards, dependent: :destroy
  has_many :tiles, dependent: :destroy

  validates_presence_of :title

  after_create do
    Tile.new(lobby_id: self.id, body: "FREE").save!
  end

  def generate_tiles(count)
    self.tiles << Array.new(count).fill { |index| Tile.new(body: index + 1) }
  end
end

app/controllers/lobbies_controller.rb
class LobbiesController < ApplicationController
  before_action :set_lobby, only: %i[ show edit update destroy generate_tiles ]

  # GET /lobbies or /lobbies.json
  def index
    @lobbies = Lobby.all
  end

  # GET /lobbies/1 or /lobbies/1.json
  def show
  end

  # GET /lobbies/new
  def new
    @lobby = Lobby.new
  end

  # GET /lobbies/1/edit
  def edit
  end

  # POST /lobbies or /lobbies.json
  def create
    @lobby = Lobby.new(lobby_params)

    respond_to do |format|
      if @lobby.save
        format.html { redirect_to edit_lobby_url(@lobby), notice: "Lobby was successfully created." }
        format.json { render :show, status: :created, location: @lobby }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lobbies/1 or /lobbies/1.json
  def update
    respond_to do |format|
      if @lobby.update(lobby_params)
        format.html { redirect_to lobby_url(@lobby), notice: "Lobby was successfully updated." }
        format.json { render :show, status: :ok, location: @lobby }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lobby.errors, status: :unprocessable_entity }
      end
    end
  end

  def generate_tiles
    respond_to do |format|
      if @lobby.generate_tiles(generate_tiles_params[:count].to_i)
        format.html { redirect_to edit_lobby_url(@lobby), notice: "Tiles were successfully generated." }
        format.json { render :show, status: :ok, location: @lobby }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: "Tiles were not generated.", status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lobbies/1 or /lobbies/1.json
  def destroy
    @lobby.destroy!

    respond_to do |format|
      format.html { redirect_to lobbies_url, notice: "Lobby was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lobby
      @lobby = Lobby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lobby_params
      params.require(:lobby).permit(:title)
    end

    def generate_tiles_params
      params.permit(:count)
    end
end

app/helpers/lobbies_helper.rb
module LobbiesHelper
end

app/views/lobbies/_form.html.erb
<% if lobby.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(lobby.errors.count, "error") %> prohibited this lobby from being saved:</h2>

    <ul>
      <% lobby.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="lobby">
  <%= form_with(model: lobby, id: "form") do |form| %>
    <%= form.label :title, style: "display: block;" %>
    <%= form.text_field :title %>
  <% end %>
  <%= yield %>
</div>

app/views/lobbies/_lobby.html.erb
<b style="grid-column: 1; grid-row: 1;"><%= lobby.title %></b>
<i style="grid-column: 1; grid-row: 2;">Players: <%= lobby.cards.count %></i>
<%= yield %>

app/views/lobbies/edit.html.erb
<% if notice %><p class="notice"><%= notice %></p><% end %>

<h2>Lobby</h2>

<%= render "form", lobby: @lobby do %>
  <%= button_tag "Update", form: "form" %>
  <%= button_to "Destroy", @lobby, method: :delete %>
  <%= button_to "Cancel", @lobby, method: :get %>
<% end %>

<h2>Tiles</h2>

<div id="tiles">
  <% @lobby.tiles.each do |tile| %>
    <%= link_to edit_lobby_tile_path(@lobby, tile) do %>
      <%= render tile %>
    <% end %>
  <% end %>
  <%= link_to new_lobby_tile_path(@lobby) do %>
    <div class="new tile">Add new tile</div>
  <% end %>
</div>

<%= form_tag(controller: "lobbies", action: "generate_tiles") do %>
  <%= label_tag "Automatically generate number of tiles:" %>
  <%= number_field_tag :count %>
  <%= submit_tag %>
<% end %>

app/views/lobbies/index.html.erb
<% if notice %><p class="notice"><%= notice %></p><% end %>

<h2>Lobbies</h2>

<ul id="lobbies">
  <% @lobbies.each do |lobby| %>
    <li class="lobby">
      <%= render lobby do %>
        <%= button_to "Join", lobby, method: :get, form: { style: "grid-row: 1;" } %>
      <% end %>
    </li>
  <% end %>
  <li class="lobby">
    <%= link_to "+ New lobby", new_lobby_path %>
  </li>
</ul>

app/views/lobbies/new.html.erb
<h2>Lobby</h2>

<%= render "form", lobby: @lobby do %>
  <%= button_tag "Create", form: "form" %>
  <%= button_to "Cancel", lobbies_path, method: :get %>
<% end %>

app/views/lobbies/show.html.erb
<% if notice %><p class="notice"><%= notice %></p><% end %>

<h2>Lobby</h2>

<header id="<%= dom_id @lobby %>" class="lobby">
  <%= render @lobby do %>
    <%= button_to "Edit", edit_lobby_path(@lobby), method: :get, form: { style: "grid-row: 1;" } %>
    <%= button_to "Exit", lobbies_path(@lobby), method: :get, form: { style: "grid-row: 1;" } %>
  <% end %>
</header>

<% if @lobby.tiles.count < 24 %>
  <p style="color: red">
    Lobby requires more tiles before creating players.
    Press "Edit" to create more tiles.
  </p>
<% end %>

<h2>Winners</h2>
<ul id="players">
  <% @lobby.cards.winners.each do |card| %>
    <li class="player winner">
      <%= link_to card.title, [@lobby, card] %>
    </li>
  <% end %>
</ul>

<h2>Players</h2>
<ul id="players">
  <% @lobby.cards.each do |card| %>
    <li class="player">
      <%= link_to card.title, [@lobby, card] %>
    </li>
  <% end %>
  <% if @lobby.tiles.count >= 24 %>
    <li class="player">
      <%= link_to "+ Join the game!", new_lobby_card_path(@lobby) %>
    </li>
  <% end %>
</ul>