config/routes.rb
Rails.application.routes.draw do
  get 'card_tiles/update'
  resources :lobbies do
    post :generate_tiles, on: :member
    resources :tiles, except: [:index, :show]
    resources :cards, except: [:index] do
      resources :tiles, controller: :card_tiles, only: [:update]
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lobbies#index"
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :lobby
  has_many :card_tiles, -> { order(id: :desc) }, dependent: :destroy
  accepts_nested_attributes_for :card_tiles
  has_many :tiles, through: :card_tiles

  scope :winners, -> { where.not(won_at: nil).order(:won_at) }

  validates_presence_of :title

  def has_won?
    horizontal_rows = [
      card_tiles.slice(0, 5),
      card_tiles.slice(5, 5),
      card_tiles.slice(10, 5),
      card_tiles.slice(15, 5),
      card_tiles.slice(20, 5)
    ]
    vertical_rows = horizontal_rows.transpose
    diagonal_rows = [
      horizontal_rows.map.with_index { |row, index| row[index] },
      horizontal_rows.reverse.map.with_index { |row, index| row[index] },
    ]

    horizontal_rows.any? { |row| row.all? { |card_tile| card_tile.marked } } or
      vertical_rows.any? { |row| row.all? { |card_tile| card_tile.marked } } or
      diagonal_rows.any? { |row| row.all? { |card_tile| card_tile.marked } }
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_lobby
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
    sampled_tiles = @lobby.tiles.where.not(body: "FREE").sample(24)
    @card.tiles = sampled_tiles.slice(0, 12) + [@lobby.tiles.find_by!(body: "FREE")] +  sampled_tiles.slice(12..)
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params.merge(lobby_id: @lobby.id))

    respond_to do |format|
      if @card.save
        format.html { redirect_to lobby_card_url(@lobby, @card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params.except(:card_tiles_attributes))
        format.html { redirect_to lobby_card_url(@lobby, @card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy!

    respond_to do |format|
      format.html { redirect_to lobby_url(@lobby), notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lobby
      @lobby = Lobby.find(params[:lobby_id])
    end

    def set_card
      @card = Card.preload(:card_tiles, :tiles).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:title, card_tiles_attributes: [:tile_id])
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div class="player">
  <%= card.title %>
  <%= button_to "Edit", edit_lobby_card_path(@lobby, @card), method: :get %>
  <%= button_to "Exit", lobby_path(@lobby), method: :get %>
</div>

<%= render "tiles", card: card %>

app/views/cards/_form.html.erb
<% if card.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

    <ul>
      <% card.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="player">
  <%= form_with(model: [@lobby, card], id: "form") do |form| %>
    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <%= form.fields_for :card_tiles do |card_tiles_form| %>
      <%= card_tiles_form.hidden_field :tile_id %>
    <% end %>
  <% end %>
  <%= yield %>
</div>

app/views/cards/_tiles.html.erb
<div id="card">
  <div>B</div>
  <div>I</div>
  <div>N</div>
  <div>G</div>
  <div>O</div>
  <% if card.persisted? %>
    <% card.card_tiles.each.with_index do |card_tile| %>
      <%= button_to [@lobby, card, card_tile.tile], class: ["tile", card_tile.marked && "marked"], method: :patch, params: { tile: { marked: !card_tile.marked } } do %>
        <%= card_tile.tile.body %>
      <% end %>
    <% end %>
  <% else %>
    <% card.tiles.each.with_index do |tile| %>
      <div class="tile">
        <%= tile.body %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/cards/edit.html.erb
<h2>Lobby</h2>

<div class="lobby">
  <%= @lobby.title %>
</div>

<h2>Card</h2>

<%= render "form", card: @card do %>
  <%= button_tag "Update", form: "form" %>
  <%= button_to "Destroy", [@lobby, @card], method: :delete %>
  <%= button_to "Cancel", [@lobby, @card], method: :get %>
<% end %>

app/views/cards/new.html.erb
<h2>Lobby</h2>

<div class="lobby">
  <%= @lobby.title %>
</div>

<h2>Card</h2>

<%= render "form", card: @card do %>
  <%= button_tag "Create", form: "form" %>
  <%= button_to "Cancel", lobby_path(@lobby), method: :get %>
<% end %>

<%= render "tiles", card: @card %>

app/views/cards/show.html.erb
<% if notice %><p class="notice"><%= notice %></p><% end %>

<h2>Lobby</h2>

<div class="lobby">
  <%= @lobby.title %>
</div>

<h2>Card</h2>

<%= render @card %>